### ISSUE TITLE
Embed higher resolution artwork

### ISSUE THREAD

**Issue by cristianst85** [jerry08/SoundCloudDownloader#1]
Hello.

This is a nice piece of software that works well for my use case.

What I noticed is that the application is embedding the artwork from the `ArtworkUrl` which may be of a lower resolution (not sure if this is always true). I think we could use the same code from the `TrackToHighestQualityArtworkUrlConverter` in `InjectThumbnailAsync` to try to embed a higher resolution artwork (i.e., to replace `large` or `small` with `t500x500`). 

If you want, I can submit a pull request with the change.

**Comment by jerry08** [comment]
Hey. Thank you!

Thanks for your assistance!! I just fixed it so I'll post an update now.
