### ISSUE TITLE
The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by jinqiufeng** [jerry08/SoundCloudDownloader#10]
Hey. After the update I got this error. How can I fix this?

**Comment by jerry08** [comment]
Can you post a screenshot of the error?

**Comment by jinqiufeng** [comment]
> Can you post a screenshot of the error?

![1](https://github.com/user-attachments/assets/00907643-8ce2-42e5-a791-6f710ba7570a)

**Comment by jerry08** [comment]
Copy the entire message and paste it here so I can see all the details. The last few lines should give me an idea of where it's crashing.

**Comment by jinqiufeng** [comment]
System.Net.Http.HttpRequestException: The SSL connection could not be
established, see inner exception.
-> System.IO.IOException: Unable to read data from the transport
connection: Удаленный хост принудительно разорвал существующее
подключение..
--> System.Net.Sockets.SocketException (10054): удаленный Xост
принудительно разорвал существующее подключение.
-End of inner exception stack trace-
at
System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowExcept
ion(SocketError, CancellationToken) + 0x47
at
System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Thre
ading.Tasks.Sources. ValueTaskSource<System.Int32>.GetResult(Int16) +
0x58
at System.Net.Security.SslStream.<EnsureFullTlsFrameAsync>d_
161'1.MoveNext()+0x191
--End of stack trace from previous location-
at System.Runtime.ExceptionServices.Exception DispatchInfo. Throw() +
0x20
at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore
1.ThrowForFailedGetResult()+0x13
at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore
1.GetResult(Int16)+0x2b
at
System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder
1.StateMachineBox 1.System.Threading.Tasks.Sources.IValueTaskSource<
TResult>.GetResult(Int16)+0x20
at System.Net.Security.SslStream.<ReceiveHandshakeFrameAsync>d_
151'1.MoveNext()+0x17b
-End of stack trace from previous location-
at System.Runtime.ExceptionServices.Exception DispatchInfo.Throw() +
0x20
at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Tas
k)+0xb2
at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDe buggerNotification(Task, ConfigureAwaitOptions)+0x4b
at System.Net.Security.SslStream.<ForceAuthenticationAsync>d___
150'1.MoveNext()+0x75b
-End of stack trace from previous location-
at System.Runtime.ExceptionServices.ExceptionDispatchinfo.Throw() +
0x20
at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Tas
k)+0xb2
at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions)+0x4b
at System.Net.Security.SslStream.<ForceAuthenticationAsync>d_
150'1.MoveNext()+0x75b
-End of stack trace from previous location-
at System.Runtime.ExceptionServices.ExceptionDispatchInfo. Throw() +
0x20
at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Tas
k)+0xb2
at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDe buggerNotification(Task, ConfigureAwaitOptions)+0x4b
at System.Net.Http.ConnectHelper.<EstablishSslConnectionAsync>d___
2.MoveNext()+0x160
-End of inner exception stack trace -
at System.Net.Http.ConnectHelper.<EstablishSslConnectionAsync>d_
2.MoveNext()+0x422
-End of stack trace from previous location-
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Tas
k)+0xb2
at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDe buggerNotification(Task, ConfigureAwaitOptions)+0x4b
at System.Net.Http.HttpConnectionPool.<ConnectAsync>d___ 103.MoveNext() + Oxbe9
-End of stack trace from previous location-
at System.Runtime.ExceptionServices.ExceptionDispatchinfo.Throw() + 0x20
at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Tas
k)+0xb2
at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions)+0x4b
at System.Net.Http.HttpConnectionPool.<CreateHttp 11 ConnectionAsync>d_105.MoveNext()+0x1d3 -End of stack trace from previous location-
at System.Runtime.ExceptionServices.ExceptionDispatchinfo.Throw() +
0x20
at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Tas
k)+0xb2
at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDe buggerNotification(Task, ConfigureAwaitOptions)+0x4b
at System.Net.Http.HttpConnectionPool.<AddHttp 11 ConnectionAsync>d_79.MoveNext()+0x31d -End of stack trace from previous location-
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +
0x20
at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Tas
k)+0xb2
at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDe buggerNotification(Task, ConfigureAwaitOptions)+0x4b
at System.Threading.Tasks.TaskCompletionSourceWithCancellation
1.<WaitWithCancellationAsync>d_1.MoveNext()+0x162
-End of stack trace from previous location-
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +
0x20
at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Tas
k)+0xb2 at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x4b
at
System.Net.Http.HttpConnectionPool.<SendWithVersion DetectionAndRetry
Async>d_89.MoveNext()+0xbe8
-End of stack trace from previous location-
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +
0x20
at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Tas
k)+0xb2
at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions)+0x4b
at System.Net.Http.RedirectHandler.<SendAsync>d_4.MoveNext() + 0x18b
-End of stack trace from previous location-
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Tas
k)+0xb2 at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions)+0x4b
at System.Net.Http.HttpClient.<<SendAsync>g_Core183_0>d.MoveNext() +0x3b1
-End of stack trace from previous location -
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +
0x20
at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Tas
k)+0xb2
at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions)+0x4b
at
SoundCloudExplode.Utils.Extensions.HttpExtensions.<ExecuteAsync>d___
1.MoveNext()+0x166
-End of stack trace from previous location-
at System.Runtime.ExceptionServices.ExceptionDispatchinfo.Throw() +
0x20
at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Tas
k)+0xb2 at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions)+0x4b
at
Explode.Utils.Extensions.HttpExtensions.<ExecuteGetAsync>d
SoundCloud __0.MoveNext()+0x225
-End of stack trace from previous location-
at System.Runtime.ExceptionServices.Exception Dispatchinfo.Throw() +
0x20
at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Tas
k)+0xb2
at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions)+0x4b
at SoundCloudExplode.SoundCloudClient.<GetClientIdAsync>d___
28.MoveNext()+0x166
-End of stack trace from previous location-
at System.Runtime.ExceptionServices.ExceptionDispatchinfo.Throw() +
0x20
at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Tas
k)+0xb2
at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions)+0x4b
at SoundCloudExplode.SoundCloudClient.<InitializeAsync>d___
27.MoveNext() + Oxaa
-End of stack trace from previous location-
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +
0x20
at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Tas
k)+0xb2
at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x4b
at
SoundCloud Downloader.Core.Resolving.QueryResolver.<ResolveAsync>d___ 1.MoveNext()+0x117
--End of stack trace from previous location -
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +
0x20
at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Tas
k)+0xb2 at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions)+0x4b
at
SoundCloud Downloader.Core.Resolving.QueryResolver.<ResolveAsync>d_2.MoveNext()+0x117
-End of stack trace from previous location-
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +
0x20
at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Tas
k)+0xb2
at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x4b
at
SoundCloudDownloader.ViewModels.Components.DashboardViewModel.<
ProcessQueryAsync>d_22.MoveNext()+0x217

**Comment by jerry08** [comment]
Try accessing this URL in your browser: https://api-v2.soundcloud.com/resolve?url=https://soundcloud.com/purityy79/dororo-op-piano-sheet-in-description&client_id=wDSKS1Bp8WmdlRPkZ7NQXGs67PMXl2Nd

If you get an error, Soundcloud's API probably has an issue in your country. If the link works, you can send me the link to the track you're trying to download so I can test it on my end.

**Comment by jinqiufeng** [comment]
Yep, seems like that. I just launched it with VPN and everything worked. Thanks!
