### ISSUE TITLE
All Downloads failed

### ISSUE THREAD

**Issue by K1rnn** [jerry08/SoundCloudDownloader#11]
Hi!
I never used github before so sorry for the lack of knowledge. Everytime i try to download my playlist all downloads come up as failed immediately. Any fixes? Thanks in advance

**Comment by jerry08** [comment]
Thanks for raising this issue. I just tried it and got the same problem. This is happening because SoundCloud's `clientId` was changed. I'll post an update that fixes it and future ones.

**Comment by K1rnn** [comment]
thanks for the reply and the fix, doing gods work!!!
