### ISSUE TITLE
1 and 1/2 Problems

### ISSUE THREAD

**Issue by itsmetoolala** [jerry08/SoundCloudDownloader#5]
Hey there!

It is by far the best program for downloading soundcloud MP3s!
Many thanks for this!
I just found it earlier after sorting out the competition ;-)

But there is a problem and a half problem!

1.)
When I download files, the author is not indicated in the file names.
In the "TAG" everything works fine and there the author is also shown to me.
However, not in the filename!
It just says this: "[04] - $author - summertime.mp3".
("summertime.mp3" is a made up title as an example)
So I think this is a bug that should be fixed because it constantly says $author on every downloaded song.

2.) (the half problem)
When I download a playlist, everything works, but I don't want to have to see these nonsensical "brackets" -> [00].
Not one of my thousands of MP3s has something like that. (I'm very strict about this)
There are always just the numbers in front. (Under 10 each with a 0 (zero) prefixed).
Example:
04 example author - example album - example song.mp3

I would like to have changed this please absolutely. For this you can surely include a function or, if the creator does not want (which is then a bit strange) get the hint where I can remove this please.
Thank you very much!

Otherwise, the program is really great! Many thanks for this!

Sincerely, itsmetoolala

Translated with www.DeepL.com/Translator (free version)

**Comment by jerry08** [comment]
Thank you very much! I'm glad you like it. I fixed the issue in the latest version regarding both of the problems you mentioned. I hadn't tested the filename template before but now I did. Thanks.
