### ISSUE TITLE
SOLVED! Error on my part: Artist/Author still doesn't show up

### ISSUE THREAD

**Issue by itsmetoolala** [jerry08/SoundCloudDownloader#6]
Hey,

since my last Issue #5 I'm glad you are working on it to fix that. <3
"$num" is now working right.
Thank you very much so far!!!

But unfortunately "$author" still isn't work.

I tried to download different songs but I always see like this:
"01 exampletrackname - §author.mp3"

I hope you can fix that. ;-)

Sincerely, itsmetoolala

**Comment by jerry08** [comment]
I tested it and it seems to work fine for me. Can you send me a link of what you're trying to download so I can replicate the problem?

**Comment by jerry08** [comment]
I see you're using "§author" instead of "$author". Try using "$author" in your filename template

**Comment by itsmetoolala** [comment]
I am now fully ashamed 6 feet under. *laugh*
Could swear it doesn't work and it was here in this topic just a "typo". I am sooo sorry!!!!!
I don't know how this could happen. *blush*

YES IT WORKS SOOO GREAT NOW!

Thank you very very much!!!!

Sincerely, blushed itsmetoolala <3

**Comment by jerry08** [comment]
Haha no problem ;-)

If you encounter any more problems or have new ideas, let me know.

**Comment by itsmetoolala** [comment]
I will. Thank you!!! <3
