### ISSUE TITLE
Track Number from Soundcloud Albums

### ISSUE THREAD

**Issue by MarkAlanJones** [jerry08/SoundCloudDownloader#7]
Nice job on GUI and nuget 

I notice that the Track NUMBER is missing in the downloaded files. It was not obvious if it is supported by the SoundCloud metadata, but the web site shows a track number.  For live albums, it is kinda important to keep the tracks in the right order.

e.g. https://soundcloud.com/johnnythundersofficial/sets/live-from-zuerich-1985

**Comment by jerry08** [comment]
You can add the track number when downloading tracks by navigating to **Settings** -> **File name template**. The default file name template is set to only use the title of the tracks.

**Comment by MarkAlanJones** [comment]
and that affects the ID3 tags it writes, as well as the filename ?

i saw code for the template, but in the gui it wasn't obvious what the template format was, or what the possible variables were so i left it....let me play with it more later when i get a chance

**Comment by jerry08** [comment]
You will see the available options when you hover over the setting. The track number isn't saved in the ID3 tag though.
